error_ref_fun.nit:20,12: Error: reached end of function; expected `return` with a value.
